/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e167a807-a601-45c9-9606-9fb8689e289d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_KEmqFpvYl",
    "aws_user_pools_web_client_id": "6ihm3smgr0fqn659s8pdqhvcv6",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "ppedetector61550e0709a641be811d166e6e07e984235958-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
